"""refactor_schema_new_tables

Revision ID: 831f33093f4e
Revises: b2c3d4e5f6a7
Create Date: 2026-03-09 23:21:11.439661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '831f33093f4e'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.Enum('SEVEN_DAYS', 'ONE_MONTH', 'ALL_TIME', name='periodtype'), nullable=False),
    sa.Column('followers', sa.BigInteger(), nullable=False),
    sa.Column('total_views', sa.BigInteger(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_min_watched', sa.BigInteger(), nullable=False),
    sa.Column('total_likes', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.Enum('SEVEN_DAYS', 'ONE_MONTH', 'ALL_TIME', name='periodtype'), nullable=False),
    sa.Column('total_views', sa.BigInteger(), nullable=False),
    sa.Column('followers_gained', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('estimated_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_channel_period_snapshots_account_id'), table_name='channel_period_snapshots')
    op.drop_table('channel_period_snapshots')
    op.drop_index(op.f('ix_channel_snapshots_account_id'), table_name='channel_snapshots')
    op.drop_table('channel_snapshots')
    op.drop_index(op.f('ix_video_analytics_video_internal_id'), table_name='video_analytics')
    op.drop_table('video_analytics')
    # Drop the FK referencing platforms before dropping the platforms table
    op.drop_constraint(op.f('accounts_platform_id_fkey'), 'accounts', type_='foreignkey')
    op.drop_table('platforms')
    op.add_column('accounts', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('accounts', 'handle',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('accounts', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('accounts', 'uploads_playlist_id')
    op.drop_column('accounts', 'platform_id')
    op.drop_column('accounts', 'country')
    op.drop_column('accounts', 'avatar_url')
    op.drop_column('accounts', 'last_synced_at')
    op.drop_column('accounts', 'channel_published_at')
    op.add_column('videos', sa.Column('privacy', sa.String(), nullable=True))
    op.alter_column('videos', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_videos_account_id'), table_name='videos')
    op.drop_constraint(op.f('uq_videos_account_video'), 'videos', type_='unique')
    op.drop_column('videos', 'license_type')
    op.drop_column('videos', 'has_caption')
    op.drop_column('videos', 'current_like_count')
    op.drop_column('videos', 'tags')
    op.drop_column('videos', 'current_view_count')
    op.drop_column('videos', 'default_language')
    op.drop_column('videos', 'current_favorite_count')
    op.drop_column('videos', 'definition')
    op.drop_column('videos', 'made_for_kids')
    op.drop_column('videos', 'category_id')
    op.drop_column('videos', 'last_synced_at')
    op.drop_column('videos', 'current_comment_count')
    op.drop_column('videos', 'privacy_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('privacy_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('current_comment_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('category_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('made_for_kids', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('definition', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('current_favorite_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('default_language', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('current_view_count', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('current_like_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('has_caption', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('license_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_videos_account_video'), 'videos', ['account_id', 'video_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_videos_account_id'), 'videos', ['account_id'], unique=False)
    op.alter_column('videos', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('videos', 'privacy')
    op.add_column('accounts', sa.Column('channel_published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('accounts', sa.Column('uploads_playlist_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('accounts_platform_id_fkey'), 'accounts', 'platforms', ['platform_id'], ['id'])
    op.alter_column('accounts', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('accounts', 'handle',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('accounts', 'last_sync')
    op.drop_column('accounts', 'image_url')
    op.create_table('platforms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('platforms_pkey')),
    sa.UniqueConstraint('name', name=op.f('platforms_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('video_analytics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('video_internal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('views', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('estimated_minutes_watched', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('average_view_duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('subscribers_gained', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shares', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimated_revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['video_internal_id'], ['videos.id'], name=op.f('video_analytics_video_internal_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('video_analytics_pkey')),
    sa.UniqueConstraint('video_internal_id', 'date', name=op.f('uq_video_analytics_video_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_video_analytics_video_internal_id'), 'video_analytics', ['video_internal_id'], unique=False)
    op.create_table('channel_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('subscriber_count', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('total_view_count', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('video_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('daily_views', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('estimated_minutes_watched', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('average_view_duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('subscribers_gained', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subscribers_lost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shares', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimated_revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('channel_snapshots_account_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('channel_snapshots_pkey')),
    sa.UniqueConstraint('account_id', 'date', name=op.f('uq_channel_snapshots_account_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_channel_snapshots_account_id'), 'channel_snapshots', ['account_id'], unique=False)
    op.create_table('channel_period_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('sync_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('subscriber_count', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('total_view_count', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('video_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('views', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('estimated_minutes_watched', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('average_view_duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('subscribers_gained', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subscribers_lost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shares', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimated_revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('channel_period_snapshots_account_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('channel_period_snapshots_pkey')),
    sa.UniqueConstraint('account_id', 'period', 'sync_date', name=op.f('uq_channel_period_snapshots_account_period_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_channel_period_snapshots_account_id'), 'channel_period_snapshots', ['account_id'], unique=False)
    op.drop_table('video_statistics')
    op.drop_table('account_statistics')
    # ### end Alembic commands ###
