"""add_channel_published_at_to_accounts

Revision ID: 99f0622fa93f
Revises: 831f33093f4e
Create Date: 2026-03-10 00:29:30.220329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99f0622fa93f'
down_revision: Union[str, Sequence[str], None] = '831f33093f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('channel_published_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'channel_published_at')
    # ### end Alembic commands ###
