import type { Metadata } from "next";
import { Providers } from "@/components/providers";
import { geistMono, geistSans } from "@/app/fonts";
import { AppSidebar } from "@/components/system/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { generateStaticParams } from "@/app/i18n/generate-static-params";
import { ReactNode } from "react";
import "@/app/globals.css";

export { generateStaticParams };

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  return (
    <Providers locale={locale}>
      <SidebarProvider>
        <AppSidebar />
        <div className="flex min-h-screen flex-1 flex-col bg-background text-foreground">
          <main className="flex-1 px-6 pb-10">{children}</main>
        </div>
      </SidebarProvider>
    </Providers>
  );
}
