import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "@/components/proviers";
import { Appbar } from "@/components/system/appbar";
import { generateStaticParams } from "@/app/i18n/generate-static-params";
import { ReactNode } from "react";
import "@/app/globals.css";

export { generateStaticParams };

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers locale={locale}>
          <div className="min-h-screen bg-background text-foreground">
            <Appbar />
            <main className="px-6 pb-10">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
